// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// twdtw_f90gt
void twdtw_f90gt(NumericMatrix XM, NumericMatrix YM, NumericMatrix CM, IntegerMatrix DM, IntegerMatrix VM, IntegerMatrix SM, int N, int M, int D, int NS, NumericVector TW, bool LB, IntegerVector JB);
RcppExport SEXP _twdtw_twdtw_f90gt(SEXP XMSEXP, SEXP YMSEXP, SEXP CMSEXP, SEXP DMSEXP, SEXP VMSEXP, SEXP SMSEXP, SEXP NSEXP, SEXP MSEXP, SEXP DSEXP, SEXP NSSEXP, SEXP TWSEXP, SEXP LBSEXP, SEXP JBSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type XM(XMSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type YM(YMSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type CM(CMSEXP);
    Rcpp::traits::input_parameter< IntegerMatrix >::type DM(DMSEXP);
    Rcpp::traits::input_parameter< IntegerMatrix >::type VM(VMSEXP);
    Rcpp::traits::input_parameter< IntegerMatrix >::type SM(SMSEXP);
    Rcpp::traits::input_parameter< int >::type N(NSEXP);
    Rcpp::traits::input_parameter< int >::type M(MSEXP);
    Rcpp::traits::input_parameter< int >::type D(DSEXP);
    Rcpp::traits::input_parameter< int >::type NS(NSSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type TW(TWSEXP);
    Rcpp::traits::input_parameter< bool >::type LB(LBSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type JB(JBSEXP);
    twdtw_f90gt(XM, YM, CM, DM, VM, SM, N, M, D, NS, TW, LB, JB);
    return R_NilValue;
END_RCPP
}
// twdtw_f90
void twdtw_f90(NumericMatrix XM, NumericMatrix YM, NumericMatrix CM, IntegerMatrix DM, IntegerMatrix VM, IntegerMatrix SM, int N, int M, int D, int NS, NumericVector TW, bool LB, IntegerVector JB);
RcppExport SEXP _twdtw_twdtw_f90(SEXP XMSEXP, SEXP YMSEXP, SEXP CMSEXP, SEXP DMSEXP, SEXP VMSEXP, SEXP SMSEXP, SEXP NSEXP, SEXP MSEXP, SEXP DSEXP, SEXP NSSEXP, SEXP TWSEXP, SEXP LBSEXP, SEXP JBSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type XM(XMSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type YM(YMSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type CM(CMSEXP);
    Rcpp::traits::input_parameter< IntegerMatrix >::type DM(DMSEXP);
    Rcpp::traits::input_parameter< IntegerMatrix >::type VM(VMSEXP);
    Rcpp::traits::input_parameter< IntegerMatrix >::type SM(SMSEXP);
    Rcpp::traits::input_parameter< int >::type N(NSEXP);
    Rcpp::traits::input_parameter< int >::type M(MSEXP);
    Rcpp::traits::input_parameter< int >::type D(DSEXP);
    Rcpp::traits::input_parameter< int >::type NS(NSSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type TW(TWSEXP);
    Rcpp::traits::input_parameter< bool >::type LB(LBSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type JB(JBSEXP);
    twdtw_f90(XM, YM, CM, DM, VM, SM, N, M, D, NS, TW, LB, JB);
    return R_NilValue;
END_RCPP
}
// twdtw_cpp
void twdtw_cpp(const NumericMatrix& XM, const NumericMatrix& YM, NumericMatrix& CM, IntegerMatrix& DM, IntegerMatrix& VM, const IntegerMatrix& SM, int N, int M, int D, int NS, const NumericVector& TW, bool LB, IntegerVector& JB);
RcppExport SEXP _twdtw_twdtw_cpp(SEXP XMSEXP, SEXP YMSEXP, SEXP CMSEXP, SEXP DMSEXP, SEXP VMSEXP, SEXP SMSEXP, SEXP NSEXP, SEXP MSEXP, SEXP DSEXP, SEXP NSSEXP, SEXP TWSEXP, SEXP LBSEXP, SEXP JBSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericMatrix& >::type XM(XMSEXP);
    Rcpp::traits::input_parameter< const NumericMatrix& >::type YM(YMSEXP);
    Rcpp::traits::input_parameter< NumericMatrix& >::type CM(CMSEXP);
    Rcpp::traits::input_parameter< IntegerMatrix& >::type DM(DMSEXP);
    Rcpp::traits::input_parameter< IntegerMatrix& >::type VM(VMSEXP);
    Rcpp::traits::input_parameter< const IntegerMatrix& >::type SM(SMSEXP);
    Rcpp::traits::input_parameter< int >::type N(NSEXP);
    Rcpp::traits::input_parameter< int >::type M(MSEXP);
    Rcpp::traits::input_parameter< int >::type D(DSEXP);
    Rcpp::traits::input_parameter< int >::type NS(NSSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type TW(TWSEXP);
    Rcpp::traits::input_parameter< bool >::type LB(LBSEXP);
    Rcpp::traits::input_parameter< IntegerVector& >::type JB(JBSEXP);
    twdtw_cpp(XM, YM, CM, DM, VM, SM, N, M, D, NS, TW, LB, JB);
    return R_NilValue;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_twdtw_twdtw_f90gt", (DL_FUNC) &_twdtw_twdtw_f90gt, 13},
    {"_twdtw_twdtw_f90", (DL_FUNC) &_twdtw_twdtw_f90, 13},
    {"_twdtw_twdtw_cpp", (DL_FUNC) &_twdtw_twdtw_cpp, 13},
    {NULL, NULL, 0}
};

RcppExport void R_init_twdtw(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
