# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

twdtw_cpp <- function(XM, YM, CM, DM, VM, SM, N, M, D, NS, TW, LB, JB) {
    invisible(.Call(`_twdtw_twdtw_cpp`, XM, YM, CM, DM, VM, SM, N, M, D, NS, TW, LB, JB))
}

twdtw_f90gt <- function(XM, YM, CM, DM, VM, SM, N, M, D, NS, TW, LB, JB) {
    invisible(.Call(`_twdtw_twdtw_f90gt`, XM, YM, CM, DM, VM, SM, N, M, D, NS, TW, LB, JB))
}

twdtw_f90 <- function(XM, YM, CM, DM, VM, SM, N, M, D, NS, TW, LB, JB, tw_r) {
    invisible(.Call(`_twdtw_twdtw_f90`, XM, YM, CM, DM, VM, SM, N, M, D, NS, TW, LB, JB, tw_r))
}

