# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

twdtw_cpp <- function(XM, YM, CM, DM, VM, N, M, D, TW, LB, JB, CL) {
    invisible(.Call(`_twdtw_twdtw_cpp`, XM, YM, CM, DM, VM, N, M, D, TW, LB, JB, CL))
}

twdtw_f90gt <- function(XM, YM, CM, DM, VM, N, M, D, TW, LB, JB, CL) {
    invisible(.Call(`_twdtw_twdtw_f90gt`, XM, YM, CM, DM, VM, N, M, D, TW, LB, JB, CL))
}

twdtw_f90 <- function(XM, YM, CM, DM, VM, N, M, D, TW, LB, JB, CL, tw_r_fun = NULL) {
    invisible(.Call(`_twdtw_twdtw_f90`, XM, YM, CM, DM, VM, N, M, D, TW, LB, JB, CL, tw_r_fun))
}

